version: '3.9'

services:
  db:
    image: postgres:15
    container_name: fictitious_order_system_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fictitious_order_system
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fictitious_order_system_backend
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: sh ./entrypoint.sh

volumes:
  pgdata:
